name = "bluish-grey"
version = "1.0.0"

[deployment]
permission = "public"
nodes = 1

[build]
dir = "build"
entry = "bluish-grey_debug.wasm"
command = "npm run build:debug"

[build_release]
dir = "build"
entry = "bluish-grey.wasm"
command = "npm run build:release"
